repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: "^thirdparty"
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: "^thirdparty"
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: '^(thirdparty|.*\.min\.js|.*\.map|.*\.svg)'
      - id: ruff-format
        exclude: '^(thirdparty|.*\.min\.js|.*\.map|.*\.svg)'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: check spelling
        exclude: '^(thirdparty|.*\.min\.js|.*\.map|.*\.svg)'
        args: [-L, "speaches,ue"]
